[GlobalDefaults DeviceProfile]
; This section overrides the default texture groups, in this case it defines the UI With Mips category named in DefaultEngine.ini
; Any changes here are inherited by any device profiles that do not override this lod group
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,MinLODSize=32,MaxLODSize=2048,LODBias=0,MipFilter=point,MipGenSettings=TMGS_SimpleAverage)
